# Architecture
arch: ResNet18

# ===== Dataset ===== #
data: /home/yuanye/data
set: CIFAR10
name: debug_runs

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: cifar_piecewise

# ===== Network training config ===== #
epochs: 160
weight_decay: 0.0005
momentum: 0.9
batch_size: 256

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
freeze_weights: True
prune_rate: -1 # Override
init: kaiming_normal
mode: fan_in
nonlinearity: relu

# ===== Hardware setup ===== #
workers: 32